# Generated by Django 5.1.3 on 2025-06-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CUIT', models.BigIntegerField()),
                ('cp', models.IntegerField()),
                ('name', models.TextField()),
                ('province', models.TextField()),
                ('locality', models.TextField()),
                ('direction', models.TextField()),
                ('soil', models.TextField()),
            ],
        ),
    ]
