# Generated by Django 5.1.3 on 2025-03-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cp',
            field=models.IntegerField(),
        ),
    ]
