# Generated by Django 5.1.3 on 2025-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0002_alter_business_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='CUIT',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
