# Generated by Django 5.1.3 on 2025-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0003_business_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='direction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='locality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='province',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='soil',
            field=models.TextField(),
        ),
    ]
