# Generated by Django 5.1.3 on 2025-06-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationimage',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='abstractModels.observablemodel'),
        ),
    ]
