# Generated by Django 5.1.3 on 2025-06-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Measurements', '0001_initial'),
        ('Sectors', '0001_initial'),
        ('abstractModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Javelin',
            fields=[
                ('connectionpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.connectionpoint')),
                ('measurementValue', models.FloatField()),
                ('connection', models.TextField()),
                ('type', models.TextField()),
                ('status', models.TextField()),
                ('usoPat', models.TextField()),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.patmeasurement')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sectors.sector')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.connectionpoint',),
        ),
    ]
