# Generated by Django 5.1.3 on 2025-03-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Javelins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javelin',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
