# Generated by Django 5.1.3 on 2025-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Javelins', '0002_alter_javelin_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javelin',
            name='business',
        ),
        migrations.AddField(
            model_name='javelin',
            name='connection',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='javelin',
            name='status',
            field=models.CharField(default='Empty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='javelin',
            name='type',
            field=models.CharField(default='Empty', max_length=100),
            preserve_default=False,
        ),
    ]
