# Generated by Django 5.1.3 on 2025-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Javelins', '0005_alter_javelin_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javelin',
            name='connection',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='javelin',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='javelin',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='javelin',
            name='usoPat',
            field=models.TextField(),
        ),
    ]
