# Generated by Django 5.1.3 on 2025-06-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Javelins', '0006_alter_javelin_connection_alter_javelin_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javelin',
            name='observations',
        ),
    ]
