# Generated by Django 5.1.3 on 2025-03-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='calibrationDate',
            field=models.DateField(),
        ),
    ]
