# Generated by Django 5.1.3 on 2025-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0002_alter_tool_calibrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='brand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='model',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='serial',
            field=models.TextField(),
        ),
    ]
