# Generated by Django 5.1.3 on 2025-03-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panels', '0003_alter_panel_hasbar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
