# Generated by Django 5.1.3 on 2025-04-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Measurements', '0004_difmeasurement_patmeasurement_and_more'),
        ('Panels', '0004_alter_panel_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.patmeasurement'),
        ),
    ]
