# Generated by Django 5.1.3 on 2025-06-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panels', '0005_alter_panel_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='observation',
        ),
    ]
