# Generated by Django 5.1.7 on 2025-03-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('I', models.SmallIntegerField()),
                ('deltaN', models.SmallIntegerField()),
                ('half', models.SmallIntegerField()),
                ('In', models.FloatField()),
                ('twoIn', models.FloatField()),
                ('fiveIn', models.FloatField()),
                ('degrees', models.FloatField()),
                ('observations', models.CharField(max_length=100)),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.measurement')),
            ],
        ),
    ]
