# Generated by Django 5.1.3 on 2025-06-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Measurements', '0001_initial'),
        ('Panels', '0001_initial'),
        ('Sectors', '0001_initial'),
        ('abstractModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreaker',
            fields=[
                ('observablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.observablemodel')),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('I', models.SmallIntegerField()),
                ('deltaN', models.SmallIntegerField()),
                ('half', models.SmallIntegerField()),
                ('In', models.FloatField()),
                ('twoIn', models.FloatField()),
                ('fiveIn', models.FloatField()),
                ('degrees', models.FloatField()),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.difmeasurement')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Panels.panel')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sectors.sector')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.observablemodel',),
        ),
    ]
