# Generated by Django 5.1.7 on 2025-03-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CircuitBreakers', '0001_initial'),
        ('Panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitbreaker',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Panels.panel'),
        ),
    ]
