# Generated by Django 5.1.3 on 2025-03-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CircuitBreakers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitbreaker',
            name='observations',
            field=models.TextField(),
        ),
    ]
