# Generated by Django 5.1.3 on 2025-03-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CircuitBreakers', '0003_alter_circuitbreaker_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitbreaker',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
