# Generated by Django 5.1.3 on 2025-04-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CircuitBreakers', '0005_alter_circuitbreaker_measurement'),
        ('Sectors', '0002_rename_business_sector_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitbreaker',
            name='sector',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Sectors.sector'),
            preserve_default=False,
        ),
    ]
