# Generated by Django 5.1.3 on 2025-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CircuitBreakers', '0007_alter_circuitbreaker_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitbreaker',
            name='brand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='model',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='name',
            field=models.TextField(),
        ),
    ]
