# Generated by Django 5.1.3 on 2025-06-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CircuitBreakers', '0008_alter_circuitbreaker_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuitbreaker',
            options={'base_manager_name': 'objects'},
        )
    ]
