# Generated by Django 5.1.7 on 2025-03-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Measurements', '0001_initial'),
        ('abstractModels', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.FloatField()),
                ('correctColor', models.BooleanField()),
                ('startConnectionPointType', models.CharField(max_length=100)),
                ('endConnectionPointType', models.CharField(max_length=100)),
                ('observations', models.CharField(max_length=100)),
                ('endConnectionPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_connectors', to='abstractModels.connectionpoint')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.measurement')),
                ('startConnectionPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_connectors', to='abstractModels.connectionpoint')),
            ],
        ),
    ]
