# Generated by Django 5.1.3 on 2025-06-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Measurements', '0001_initial'),
        ('abstractModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('observablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.observablemodel')),
                ('name', models.TextField()),
                ('section', models.FloatField()),
                ('correctColor', models.BooleanField()),
                ('startConnectionPointType', models.TextField()),
                ('endConnectionPointType', models.TextField()),
                ('endConnectionPoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_connectors', to='abstractModels.connectionpoint')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.patmeasurement')),
                ('startConnectionPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_connectors', to='abstractModels.connectionpoint')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.observablemodel',),
        ),
    ]
