# Generated by Django 5.1.3 on 2025-03-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectors', '0001_initial'),
        ('abstractModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='endConnectionPoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_connectors', to='abstractModels.connectionpoint'),
        ),
    ]
