# Generated by Django 5.1.3 on 2025-03-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectors', '0002_alter_connector_endconnectionpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
