# Generated by Django 5.1.3 on 2025-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectors', '0004_alter_connector_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='endConnectionPointType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='connector',
            name='startConnectionPointType',
            field=models.TextField(),
        ),
    ]
