# Generated by Django 5.1.3 on 2025-06-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connectors', '0005_alter_connector_endconnectionpointtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connector',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='connector',
            name='id',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='observations',
        ),
    ]
