# Generated by Django 5.1.3 on 2025-06-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connectors', '0006_alter_connector_options_remove_connector_id_and_more'),
        ('abstractModels', '0006_finalize_pk_and_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='observablemodel_ptr',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=False,
                serialize=False,
                to='abstractModels.observablemodel',
            ),
        ),
    ]