# Generated by Django 5.1.3 on 2025-06-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abstractModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.measurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.measurement',),
        ),
        migrations.CreateModel(
            name='PatMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.measurement')),
                ('dif_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.difmeasurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.measurement',),
        ),
    ]
