# Generated by Django 5.1.7 on 2025-03-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Businesses', '0001_initial'),
        ('Tools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('methodology', models.CharField(max_length=100)),
                ('observations', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Businesses.business')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tools.tool')),
            ],
        ),
    ]
