# Generated by Django 5.1.3 on 2025-03-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Measurements', '0002_alter_measurement_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
    ]
