# Generated by Django 5.1.3 on 2025-04-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Measurements', '0003_alter_measurement_enddate'),
        ('abstractModels', '0002_alter_connectionpoint_name_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.measurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.measurement',),
        ),
        migrations.CreateModel(
            name='PatMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.measurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.measurement',),
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='business',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='tool',
        ),
    ]
