# Generated by Django 5.1.3 on 2025-04-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CircuitBreakers', '0005_alter_circuitbreaker_measurement'),
        ('Connectors', '0004_alter_connector_measurement'),
        ('Javelins', '0005_alter_javelin_measurement'),
        ('Measurements', '0004_difmeasurement_patmeasurement_and_more'),
        ('Outlets', '0004_alter_outlet_measurement'),
        ('Panels', '0005_alter_panel_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
