# Generated by Django 5.1.3 on 2025-04-07 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Measurements', '0005_delete_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='patmeasurement',
            name='dif_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.difmeasurement'),
        ),
    ]
