# Generated by Django 5.1.3 on 2025-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractModels', '0002_alter_connectionpoint_name_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionpoint',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='methodology',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
