# Generated by Django 5.1.3 on 2025-06-01 21:54

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('abstractModels', '0003_alter_connectionpoint_name_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservableModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('observations', models.TextField(blank=True)),
                ('polymorphic_ctype', models.ForeignKey(
                    editable=False, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_%(app_label)s.%(class)s_set+',
                    to='contenttypes.contenttype'
                )),
            ],
        ),
        migrations.AddField(
            model_name='connectionpoint',
            name='observablemodel_ptr',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='abstractModels.observablemodel',
            ),
        ),
    ]

