# Generated by Django 5.1.3 on 2025-06-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractModels', '0005_migrate_connectionpoint_to_observable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observablemodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='observablemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
