# Generated by Django 5.1.3 on 2025-06-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractModels', '0006_finalize_pk_and_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observablemodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='connectionpoint',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='connectionpoint',
            name='observablemodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.observablemodel'),
        ),
        migrations.AlterField(
            model_name='observablemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
