# Generated by Django 5.1.7 on 2025-03-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CircuitBreakers', '__first__'),
        ('Measurements', '0001_initial'),
        ('Sectors', '0001_initial'),
        ('abstractModels', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('connectionpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstractModels.connectionpoint')),
                ('usoPat', models.CharField(max_length=50)),
                ('observations', models.CharField(max_length=200)),
                ('circuitBreaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CircuitBreakers.circuitbreaker')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Measurements.measurement')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sectors.sector')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('abstractModels.connectionpoint',),
        ),
    ]
