# Generated by Django 5.1.3 on 2025-03-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outlets', '0002_alter_outlet_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='usoPat',
        ),
    ]
