# Generated by Django 5.1.7 on 2025-03-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Scheme', models.CharField(max_length=100)),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Businesses.business')),
            ],
        ),
    ]
