# Generated by Django 5.1.3 on 2025-03-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sectors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='Business',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='Scheme',
            new_name='scheme',
        ),
    ]
