# Generated by Django 5.1.3 on 2025-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sectors', '0002_rename_business_sector_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sector',
            name='scheme',
            field=models.TextField(),
        ),
    ]
